### ISSUE TITLE
'cacert' argument to Binding::POST is actually IdP signing cert (present in metadata)

### ISSUE THREAD

**Issue by rogerrohrbach** [perl-net-saml2/perl-Net-SAML2#231]
We've just implemented verification of signed SAML assertions thus:
```perl
my $idp = Net::SAML2::IdP->new_from_url(url => $context->{SAML_METADATA_URL});
my @signing_certs = $idp->cert('signing');
my $tmp_cert_file = File::Temp->new( "$domain.cer", DIR => Globals::get_temporary_directory('saml_certs'));
write_file($tmp_cert_file, $signing_certs[0][0]);
my $post = Net::SAML2::Binding::POST->new(cacert => $tmp_cert_file->filename());
```

Just registering my bewilderment that this works.  The tutorial [says](https://github.com/perl-net-saml2/perl-Net-SAML2/blob/master/TUTORIAL.md#create-the-post-object-to-process-response) that `cacert` is a CA certificate, i.e., a certificate used to verify the authenticity of another certificate:

> This CACert should be capable of verifying at least one of the signing certificates provided in the ametadata.

But we're merely passing "one of the signing certificates."

What makes sense:

- passing the signing certificate here. This has the public key that can verify the signed XML in the response.

What doesn't:

- why the use of an actual CA cert (even if self-signed, as is usual in SAML implementations) is unnecessary, contra the documentation
- how passing only a CA cert as documented could actually work, since the POST object has no access to the IdP metadata, and thus the signing certificate
- why the library makes us copy the signing cert to a file, when it's available in the IdP metadata

I have noticed that the documentation has fallen way behind and no longer reflects many changes to the interface, so that is perhaps what's happened?

**Comment by timlegge** [comment]
I will review later today. CAcert is a little misleading as it's essentially the certificate itself in many cases. 

The purpose is obviously to allow you to validate that certificate being received with the assertion is the expected certificate. That is, the assertion is signed with a certificate that you specifically decided to trust when you downloaded it from the IDP. 

It's been called that for as long as I have been involved.

**Comment by timlegge** [comment]
> We've just implemented verification of signed SAML assertions thus:
> 
> ```perl
> my $idp = Net::SAML2::IdP->new_from_url(url => $context->{SAML_METADATA_URL});
> my @signing_certs = $idp->cert('signing');
> my $tmp_cert_file = File::Temp->new( "$domain.cer", DIR => Globals::get_temporary_directory('saml_certs'));
> write_file($tmp_cert_file, $signing_certs[0][0]);
> my $post = Net::SAML2::Binding::POST->new(cacert => $tmp_cert_file->filename());
> ```

Yes, that will potentially work however you are selecting the first certificate which may not be correct if your idp uses multiple certs in the metadata.

The metadata essentially gives you a way to grab all the required data in one file.  It has the end points (SLO, ACS, etc) as well as the signing and encryption certificates that are in use.

Most IdPs give you an option to download the metadata.xml and the certificate separately.  The certificate provided is the active one but multiple certificates may be in the metadata.xml

For example I have a demo Azure IdP "Enterprise Application"  The metadata includes the active and inactive certificate.    The certificate I can download is the active certificate.

I downloaded my metadata and extracted the two signing certs into cert1 and cert2.  I downloaded the "Certificate (Base64)" that is provided to cacert.pem (yes, its not a CA cert)

openssl verify -CAfile cacert.pem cert1
cert1: OK
openssl verify -CAfile cacert.pem cert2
CN = Microsoft Azure Federated SSO Certificate
error 18 at 0 depth lookup: self-signed certificate
error cert2: verification failed

Providing cacert to the new_from_url passes the option to the creation of the IdP object which will actually validate that the certificates in the metadata that you have retrieved can be verified  by the previously downloaded certificate.  It removed any certificates that would fail validation.   In the case where you are downloading the metadata file each time time it would allow you to be sure that the signing certificates have not changed since you last decided to trust the signing certificate/metadata.

> Just registering my bewilderment that this works. The tutorial [says](https://github.com/perl-net-saml2/perl-Net-SAML2/blob/master/TUTORIAL.md#create-the-post-object-to-process-response) that `cacert` is a CA certificate, i.e., a certificate used to verify the authenticity of another certificate:
> 
> > This CACert should be capable of verifying at least one of the signing certificates provided in the ametadata.
> 
> But we're merely passing "one of the signing certificates."

Yes, it is exactly that but doing it that way reduces the security since the metadata could change and you will continue to trust it.  That would not be a problem if you downloaded the metadata and saved it and then used new_frm_xml instead.

The signing certificate can generally also be used to validate the metadata is properly signed by the signing certificate and has not changed since it was generated.  (I just noticed though that we don't seem to have that option) 
 
> * passing the signing certificate here. This has the public key that can verify the signed XML in the response.

Yes, the metadata simply holds the data about the IdP including the certificates used to sign the Response/Assertion

> What doesn't:
> 
> * why the use of an actual CA cert (even if self-signed, as is usual in SAML implementations) is unnecessary, contra the documentation

If you are accessing the metadata each time from a URL you cannot be use the metadata has not been tampered with if you do not validate it in some way.  We use it to ensure that the certificates in the metadat have not changed (I will add a feature request for verifying signed xml in the metadata).

> * how passing only a CA cert as documented could actually work, since the POST object has no access to the IdP metadata, and thus the signing certificate

For this one you need to know how XML::Sig verifies signed XML.  Basically it will use the certificates embedded in the Response/Assertion to verify that the Response/Assertion were properly signed by the private key of the certificates provided by the XML.  So you are trusting what you received by verifying it against something included in what you received.  Whoever sent you the Response properly signed the XML.

The cacert option tells Net::SAML2 to also verify that the certificate/keypair used to sign the XML is one that you actually trust (the signing certificate).  

> * why the library makes us copy the signing cert to a file, when it's available in the IdP metadata

Because Crypt::OpenSSL::Verify that actually does that trust validation requires a file.

> I have noticed that the documentation has fallen way behind and no longer reflects many changes to the interface, so that is perhaps what's happened?

The TUTORIAL.md was written quite a while ago and almost certainly needs some updates.  Not really sure when I will get to it though.

Net::SAML2 attempts to be secure.  Many of the SAML2 specifications were less than secure so we have implemented as much additional security around it as possible.  The verification of the certificates used to sign the assertion is necessary.  My only concern with your method is that as you are downloading the metadata (each tiime?) you are trusting that no one can send you a modified metadata file as a precursor of sending you forged assertions.  A bit unlikely but...

I hope this helps.  Feel free to ask more - it was useful to refresh my memory.  If this answers your question let me know and we can close the issue or leave it for documentation

**Comment by timlegge** [comment]
#232 created to validate signed metadata

**Comment by rogerrohrbach** [comment]
> you are selecting the first certificate which may not be correct if your idp uses multiple certs in the metadata.

Our customer's (Microsoft Entra ID) IdP metadata includes the same X509 certificate at multiple levels:

- on the `EntityDescriptor`, in the `Signature`
- on the `RoleDescriptor` and `IDPSSODescriptor`, in the signing `KeyDescriptor`

but, duly noted.

> I downloaded the "Certificate (Base64)" that is provided to cacert.pem (yes, its not a CA cert)

Maybe your documentation should change.  But maybe not, if some IdPs provide a (self-signed) "CA cert."  In any case, it's a bit confusing.

> Providing cacert to the new_from_url passes the option to the creation of the IdP object which will actually validate that the certificates in the metadata that you have retrieved can be verified by the previously downloaded certificate.

Okay—this is perhaps a compelling reason to go ahead and store the certificate.  If I understand your concern aright, it's about the possibility of a man-in-the-middle attack wherein our request for IdP metadata is somehow hijacked and we receive forged metadata, which will induce us to accept forged assertions.  The stakes in our application aren't that terribly high, but this is probably just good hygiene.

> For this one you need to know how XML::Sig verifies signed XML. Basically it will use the certificates embedded in the Response/Assertion to verify that the Response/Assertion were properly signed by the private key of the certificates provided by the XML.

Ah, of course. The SAML response has the signing certificate.

> Because Crypt::OpenSSL::Verify that actually does that trust validation requires a file.

Gotcha.


We'll move to actually store a local copy of the provided certificate, and pass that when instantiating both the `IdP` and `POST` objects.
