### ISSUE TITLE
some of the uris are optional 

### ISSUE THREAD

**Issue by timlegge** [perl-net-saml2/perl-Net-SAML2#46]
https://github.com/perl-net-saml2/perl-Net-SAML2/blob/ea262ce764bf5e91d9bfb6390475e012010498b3/lib/Net/SAML2/SP.pm#L102

**Comment by waterkip** [comment]
I'm thinking out loud here.

What if we are going to have an API where you say preferred binding, eg

```
my $sp = Net::SAML2->new(
   binding => SOME_BINDING,
   ...
);
```

Based on this binding we'll make certain URI's mandatory. 

Even if we don't take this approach I would love to have make them all NOT required and have a predicate, so we can generate them when provided. This will be backwards compatible and is a fairly trivial code change I think. If people want some URI's required they can extend Net::SAML2 and make the param required.

Unrelated note:
I'd like to supply full paths to the URI's, now it is appending everything at a base URI. Perhaps if able to coerce it, we use that object otherwise we'll append it?

**Comment by waterkip** [comment]
I made a PR for this issue: https://github.com/perl-net-saml2/perl-Net-SAML2/pull/66

**Comment by waterkip** [comment]
I was looking at some of the code for the URI's and I think we can do even better. The thing is I know I want to leave out certain bindings we currently have right now.

Proposed new API to define what we need and WHY we need each URI:

```
my $sp = Net::SAML2::SP->new(
      SingleLoginService => [
          {
              binding => BINDING_HTTP_REDIRECT,
              location => 'https://foo.nl',
          },
      ],
      AssertionConsumerService => [
          # order decides index?
          {
              binding => BINDING_HTTP_ARTIFACT,
              location => ..,
              # index 1
          },
          {
              binding => BINDING_HTTP_POST,
              # index 2
              default => 1,
          }
      ],
      ...,
);
```

This also allows to setting the default so something else than HTTP-Post like we currently do.

**Comment by timlegge** [comment]
> full paths to the URI's, now it is appending everything at a base URI.

I would have to look back at this I know the base is used but I can't remember if this is for compatibility with the SAML spec or just a feature of how it was implemented in the original version
